### ISSUE TITLE
Config support deep merge.

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#1038]
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  name: calico
spec:
  path: etc/custom-resources.yaml
  strategy: merge # or overwrite
  data: |
    apiVersion: operator.tigera.io/v1
    kind: Installation
```
If the strategy is merge, then to merge the values. If the strategy is overwrite, overwrite the whole file.
