### ISSUE TITLE
build image local mode not set Clusterfile to image metadata

### ISSUE THREAD

**Issue by cuisongliu** [alibaba/sealer#107]
#### What happened:

registry.cn-qingdao.aliyuncs.com/sealer-io/cloudrootfs:v1.19.9-alpha.3 

sealer build -t  registry.cn-qingdao.aliyuncs.com/sealer-io/cloudrootfs:v1.19.9-alpha.3  . 

cat /var/lib/sealer/metadata/9ce2938527c2aff4b95e78fd961b7a19.yaml

```
kind: Image
metadata:
  creationTimestamp: null
  name: registry.cn-hongkong.aliyuncs.com/sealyun/kubernetes-amd64:v1.19.9
spec:
  hash: ""
  id: 9ce2938527c2aff4b95e78fd961b7a19
  layers:
  - hash: 245d2093fabc329a6654751f63999d7fec433de59a4ed7ca244398e2c01582ba
    type: COPY
    value: . .
  mergedLayer: ""
status: {}
```

not clusterfile config

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
