### ISSUE TITLE
upgrade version of gosec to alleviate false alarms

### ISSUE THREAD

**Issue by kakaZhou719** [alibaba/sealer#1076]
#### What happened:

Currently , we use gosec version is v2.2.0(has some bug ), and gosec latest version is v2.9.5 .meanwhile, its not the official golang security action. 

hence, i proposal we upgrade version of gosec to alleviate false alarms.

```
name: Run Gosec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golang-security-action:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

```

#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
