### ISSUE TITLE
Create config file if file not exist.

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#1085]
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  name: env
spec:
  path: etc/env.sh
  data: |
    DEVICE=vdb
```
```
bash: etc/env.sh: No such file or directory
```
