### ISSUE TITLE
kyverno doesn't mutate image registry when it's specified

### ISSUE THREAD

**Issue by shy-Xu** [alibaba/sealer#1106]
## Issue Description
With kyverno policy, if a pod declare to use image nginx:latest, we should mutate it to sea.hub:5000/nginx:latest, but if a pod declare to use image docker.io/nginx:latest, we should not mutate it.   

The kyverno version is 1.5.4, and what important is to edit the policy. it seems that current kyverno policies can support this feature well.

**Comment by shy-Xu** [comment]
Refer to this policy:
```
apiVersion : kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: redirect-registry
spec:
  background: false
  rules:
  - name: prepend-registry-containers
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
        - UPDATE
      - key: "{{images.containers.*.registry}}"
        operator: Equals
        value: ""
    mutate:
      foreach:
      - list: "request.object.spec.containers"
        patchStrategicMerge:
          spec:
            containers:
            - name: "{{ element.name }}"
              image: "sea.hub:5000/{{ images.containers.{{element.name}}.path}}:{{images.containers.{{element.name}}.tag}}"
  - name: prepend-registry-initcontainers
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
        - UPDATE
      - key: "{{images.initContainers.*.registry}}"
        operator: Equals
        value: ""
    mutate:
      foreach:
      - list: "request.object.spec.initContainers"
        patchStrategicMerge:
          spec:
            initContainers:
            - name: "{{ element.name }}"
              image: "sea.hub:5000/{{ images.initContainers.{{element.name}}.path}}:{{images.initContainers.{{element.name}}.tag}}"
```
