### ISSUE TITLE
apply failed when SSH port is not 22

### ISSUE THREAD

**Issue by sfeng1996** [alibaba/sealer#1142]
#### What happened:

apply failed when SSH port is not 22

#### Clusterfile:
```yaml
apiVersion: sealer.cloud/v2
kind: Cluster
metadata:
  name: test
spec:
  image: kubernetes:v1.19.8
  ssh:
    passwd: "xxxxxx"
    #pk: /root/.ssh/id_rsa 
    user: root
    port: "22"
  hosts:
  - ips: [172.31.97.104]
    roles: [master]
  - ips: [172.31.97.105]
    ssh:
      passwd: "xxxxxx"
      port: "2222"
```

#### Error Info:
```
2022-02-14 15:41:18 [INFO] [local.go:238] Start to create a new cluster
2022-02-14 15:41:44 [EROR] [apply.go:27] mount rootfs failed copy rootfs failed failed to copy sub files new sftp client failed dial tcp 172.31.97.105:22: connect: connection refused
```

#### Environment:

- sealer version (use `sealer version`):
v0.6.1
