### ISSUE TITLE
CloudImage license

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#1145]

**Comment by allencloud** [comment]
What is the purpose of CloudImage License?
And what is the detailed demand of it?

Could you please attach more information? @fanux

**Comment by fanux** [comment]
ADP relies on this feature, and I will add a detailed design, mainly to encrypt the image through the private key, and decrypt the image through the public key when the license plug-in is successfully executed.

**Comment by fanux** [comment]
###  Build encrypt CloudImage

```
sealer build my-encrypt-image:latest . --private-key="xxxxxxxx"
```

### decrypt CloudImage and use it

Clusterfile
```
apiVersion: sealer.cloud/v2
kind: Cluster
metadata:
  name: default-kubernetes-cluster
spec:
  image: kubernetes:v1.19.8
  ssh:
    passwd: xxx
  hosts:
    - ips: [ 192.168.0.2,192.168.0.3,192.168.0.4 ]
      roles: [ master ]
    - ips: [ 192.168.0.5 ]
      roles: [ node ]
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
  name: taint
spec:
  type: LICENSE
  data: |
      "env": "env data, collet and encrypt by license tools, like iplist CPU model and quantity...",
```
The LICENSE plugin will check the env data and decrypt the CloudImage.
