### ISSUE TITLE
I want plugin can get global env from ClusterFile

### ISSUE THREAD

**Issue by VinceCui** [alibaba/sealer#1180]
## Issue Description

Type: *feature request*

**Comment by bxy4543** [comment]
The shell plugin can use env directly, for example:
```yaml
...
spec:
  image: kubernetes:v1.19.8
  ...
  env:
    - DashBoardPort=6443
    - ips=172.17.102.186
    - ips=172.17.102.187
---
apiVersion: sealer.aliyun.com/v2alpha1
kind: Plugin
metadata:
  name: MyShell
spec:
  action: PreInstall
  type: SHELL
  data: |
    echo $DashBoardPort
    echo ${ips[@]}
```
We have other plugins: hostname Plugin,label plugin... Do you mean these plugins use env?


scripts in Kubefile  use env:
```Kubefile
...
CMD sh init_appitcation.sh
```
Env =[key1=value1] in Clusterfile to start this image:
`CMD sh init_appitcation.sh` Is equivalent to exec `key1=value1 && sh init`
