### ISSUE TITLE
Storage Device plugin

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#1190]
```
apiVersion: sealer.cloud/v2
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: kubernetes:v1.19.8
  hosts:
    - ips: [ 192.168.0.2 ]
      roles: [ master ] 
      env: 
      - StorageDevice=/dev/vdb
      - KubeletRunDiskSize=100
      - DockerRunDiskSize=100
```

plugin.yaml
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
  name: storage_device
spec:
  type: STORAGE_DEVICE
```
Copy this plugin yaml into your CloudImage to enable storage device plugin:
```
FROM kuberenetes:v1.19.8
COPY plugin.yaml plugins/
```
