### ISSUE TITLE
CMD support list and overwrite

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#1205]
```
FROM kubernetes:v1.19.8
CMD [kubectl apply -f mysql, kubectl apply -f redis, kubectl apply -f saas]
```
If you don't want to apply mysql, you can overwrite CMD in Clusterfile.

```
apiVersion: sealer.cloud/v2
kind: Cluster
metadata:
  name: default-kubernetes-cluster
spec:
  image: kubernetes:v1.19.8
  cmd:
  - kubectl apply -f redis
  - kubectl apply -f saas
```

But how to handle CMD on base image, sometimes we need to overwrite it, sometimes not...
