### ISSUE TITLE
cni插件起不来 

### ISSUE THREAD

**Issue by Xsy2002** [alibaba/sealer#1265]
What happened？
![image](https://user-images.githubusercontent.com/67572942/159232902-7431ebf5-172c-4e88-8ccc-9121530929a8.png)
![image](https://user-images.githubusercontent.com/67572942/159233002-b93ada2f-e11f-4423-a53d-2d3e652b722b.png)

**Comment by bxy4543** [comment]
Please use the `ifconfig` command to show me the IP information

**Comment by Xsy2002** [comment]
![image](https://user-images.githubusercontent.com/67572942/159235363-e2a48a6b-0224-4889-b862-014019ab6bff.png)

**Comment by bxy4543** [comment]
vi custom-resources.yaml
```yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 100.64.0.0/10
      encapsulation: IPIP
      natOutgoing: Enabled
      nodeSelector: all()
    nodeAddressAutodetectionV4:
      #  Interface enables IP auto-detection based on interfaces that match the given regex.
      interface: "em1"
```
exec :
```shell
kubectl apply -f custom-resources.yaml
