### ISSUE TITLE
api domain 不支持自定义

### ISSUE THREAD

**Issue by erdun** [alibaba/sealer#1318]
#### What happened:

api server host 固定为 `apiserver.cluster.local`, 不支持自定义

#### How to reproduce it (as minimally and precisely as possible):

sealer apply -f Clusterfile, api host 为 `apiserver.cluster.local`, 不是 `k8s-proxy.aiot-in.net`
```
apiVersion: sealer.cloud/v2
kind: Cluster
metadata:
  name: telkom
spec:
  image: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8
  aPIServerDomain:
  ssh:
    pk: /home/ops/.ssh/key.pem
    user: ops
    port: "33033"
  hosts:
    - ips: [ 10.106.1.219, 10.106.3.144, 10.106.6.225 ] # this master ssh port is different with others.
      roles: [ master ]
    - ips: [ 10.106.0.249, 10.106.4.149, 10.106.5.8, 10.106.2.29 ] # this master ssh port is different with others.
      roles: [ node ]

---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  name: etc-kubeadm
spec:
  path: etc/kubeadm.yml
  strategy: merge
  data: |
    controlPlaneEndpoint: k8s-proxy.aiot-in.net:6443
    apiServer:
      certSANs:
      - k8s-proxy.aiot-in.net
    networking:
      dnsDomain: cluster.local
      podSubnet: 10.106.64.0/18
      serviceSubnet: 10.106.128.0/18
```
