### ISSUE TITLE
config配置文件预处理，支持通过data的内容生成一个kubernetes secrect yaml文件

### ISSUE THREAD

**Issue by lyhao** [alibaba/sealer#1339]
# sealer 配置
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  name:  configxxx
spec:
  path: secrect.yaml
  process: value|tojson|tobase64|tosecret # pre process pipeline
  data:
      components:
         mysql: 
           cpu:
             request: 1000m
      global:
        abc: xxx
```
# 处理过程

1. 提取data里面的values, components 和 global是key，对应的values分别是：
```
         mysql: 
           cpu:
             request: 1000m
```
```
        abc: xxx
```
2. 把values转化成json
3. 把json转化成base64
4. 生成一个secrect.yaml，如该文件已经存在进行deepmerge 如下

# 输出 secrect.yaml
```
apiVersion: v1
data:
  global: e2FiYzogeHh4fQo=
  components: e215c3FsOntjcHU6e3JlcXVlc3Q6IDEwMDBtfX19Cg==
kind: Secret
metadata:
  name: gu-demo-configuration
  namespace: default
type: Opaque
```

secret base64解析结果：
```
# echo e215c3FsOntjcHU6e3JlcXVlc3Q6IDEwMDBtfX19Cg==|base64 -d
{mysql:{cpu:{request: 1000m}}}
```

config里的data数据被指定输出到secret里的data里同时做了数据转换
