### ISSUE TITLE
feature: image cache ability

### ISSUE THREAD

**Issue by justadogistaken** [alibaba/sealer#140]
## Issue Description

Type: *feature request*
[hack docker](https://github.com/justadogistaken/moby/pull/1) (verified)
[hack distribution](https://github.com/justadogistaken/distribution/pull/2) (verified)

### docker daemon config

/etc/docker/daemon.json

```json
{
...
"mirror-registries":[
// docker pull reg.test1.com/library/nginx:latest
// mirror reg.test1.com image to "http://mirror.test1.com" or "https://mirror.test2.com"
{
	"domain": "reg.test1.com",
	"mirrors": ["http://mirror.test1.com", "https://mirror.test2.com"]
},
// mirror all pull image request to http://sea.hub:5000
// 
{
	"domian": "*",
	"mirrors": ["http://sea.hub:5000"]
}
],
"insecure-registries": ["sea.hub:5000", "mirror.test1.com"]
...
}
```

registry config

```yaml
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
proxy:
  remoteregistries:
  # will cache image from docker pull docker.io/library/nginx:latest or docker pull nginx
  - url: https://registry-1.docker.io #dockerhub default registry
    username:
    password:
    # will cache image from docker pull reg.test1.com/library/nginx:latest
  - url: https://reg.test1.com
    username: username
    password: password
  - url: http://reg.test2.com
    username: username
    password: password
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

registry config should be mounted as /etc/docker/registry/config.yml, and mount host /var/lib/registry using -v /var/lib/registry/:/var/lib/registry/ to store image cache

### Additional context
remoteregistries could be added dynamically, but I do not store the dynamical remoteregistries info, because there would be many pair of username and password for same url probably, and maybe some image from different namespace has different auth info. Thus it's costly for adding remoteregistries dynamically, every docker pull request will generate request to real registry from local registry to get real auth endpoint.
And for making cache registry work, there must be one remoteregistries item, so I take the following config as default registry config.yml.
```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
proxy:
  remoteregistries:
  - url: https://registry-1.docker.io
    username:
    password:
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
at the runtime, I guess not everyone needs the cache ability, So I recommend turn the cache off, leave the choice to users.
the following config will turn off cache ability, and the registry will behave like the community version.
```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
docker run -v  {pathToTheConfigAbove}:/etc/docker/registry/config.yml

if you do not want to provide any remote url, depend on request to config auth info dynamically. should config registry by following way:
```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
proxy:
  on: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
