### ISSUE TITLE
infra apply IP list lack IP

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#201]
``` 
 nodes:
    count: "4"
    cpu: "4"
    dataDisks:
    - "100"
    ipList:
    - 172.16.0.149
    - 172.16.0.164
```
Only two IP address in iplist, desired is 4
