### ISSUE TITLE
--interface not work

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#227]
1. run a Cluster   sealer run kubernetes:v1.19.9 -m 172.16.0.119 -n 172.16.0.120 -p Seadent123 --interface bond0
2. show calico config 
```
[root@iZ2vcix9zcr68eg4nsq9twZ ~]# kubectl get pod -n kube-system   calico-node-2ccfr -oyaml|grep eth0
      value: interface=eth0 # it should be bond0
```
3. show Clusterfile : .sealer/my-cluster/Clusterfile
```
  network:
    cniName: calico
    interface: eth0 # should be bond0
    podCIDR: 100.64.0.0/10
    svcCIDR: 10.96.0.0/22
```
