### ISSUE TITLE
CloudImage Global config

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#268]
https://github.com/alibaba/sealer/blob/main/docs/design/global-config.md

**Comment by lllwan** [comment]
I'm going to invest in the development of this feature。

**Comment by fanux** [comment]
SaaS config file feature:

Clusterfile:
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: registry.cn-qingdao.aliyuncs.com/sealer-app/my-SAAS-all-inone:latest
  provider: BAREMETAL
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: AppConfig
metadata:
  name: mysql-config
spec:
  data: |
       mysql-user: root
       mysql-passwd: xxx
...
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: AppConfig
metadata:
  name: redis-config
spec:
  data: |
       redis-user: root
       redis-passwd: xxx
...
```
When apply this Clusterfile, sealer will generate some values file for application config. Named etc/mysql-config.yaml  etc/redis-config.yaml. 

So if you want to use those config, Kubefile is like this:

```
FROM kuberentes:v1.19.9
...
CMD helm install mysql -f etc/mysql-config.yaml
CMD helm install mysql -f etc/redis-config.yaml
```
