### ISSUE TITLE
希望能支持自定义主机名设置

### ISSUE THREAD

**Issue by ziyouguodu** [alibaba/sealer#283]
之前的版本需要自己手动设置主机名，希望sealer能支持配置文件中自定义主机名设置

**Comment by fanux** [comment]
Do you have some suggestion about the user interface of this feature. Set the hostname in Clusterfile? Or add an exec command to let you set hostname.  `sealer exec "sethostname xxx" -f Clusterfile`

**Comment by ziyouguodu** [comment]
在Clusterfile  中 ipList 加个字段主机名应该比较合理

**Comment by ziyouguodu** [comment]
example：
  masters:
    ipList:
     - 172.20.125.234 master-1
  nodes:
    ipList:
     - 172.20.126.8 node-1

**Comment by ziyouguodu** [comment]
现在ipList 是否支持范围连号？

**Comment by fanux** [comment]
> 现在ipList 是否支持范围连号？

Not support now, you can provide this feature.

**Comment by fanux** [comment]
> example：
> masters:
> ipList:
> - 172.20.125.234 master-1
> nodes:
> ipList:
> - 172.20.126.8 node-1

Maybe we need upgrade the Clusterfile definition.

**Comment by fanux** [comment]
Maybe we can provide a plugin to do this.

1. define hostname plugin config
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: PluginConfig
metadata:
  name: hostname-config
spec:
  plugin: hostname
  data: |
      - name: master-0
         ip: 172.20.125.234
```

2. develop a plugin processor
```
type Plugin interface {
   Process(*v1.Cluster, *v1.PluginConfig) error
}
```
