### ISSUE TITLE
more params for init cluster

### ISSUE THREAD

**Issue by hhstu** [alibaba/sealer#313]
1. 尽量暴漏 kubeadm 的配置文件防止硬编码给交付人员集群调优最大的灵活性， 
2. 集群上层的应用 插件化 按需安装，
3. 参数按重要程度或修改频率自上而下排列， 
4. 当前配置节点的参数过于简陋，交付现场可能不同主机密码或者网卡不同

下边是暂时我期望的配置模板：

``` yaml

# 配置会和 命令行参数 深度 merge

# 集群名 必填
name:
# 集群类型，支持：kubernetes || k3s，     必填
cluster_type: kubernetes
# 集群 vip 地址, example: 172.20.72.48, 必填
load_balancer: ""
# chartmuseum仓库地址，为空时会在 master[0]自动创建, example: http://172.20.60.48:5001
chartmuseum_url: ""
# 镜像仓库地址，为空时会在 master[0]自动创建, example: http://172.20.60.48:5000
registry_url: ""
# 全局 用户名 密码
default_username: root
default_password:
# 至少一个 master 节点
masters:
  - hostname: "" # 覆盖节点 hostname
    #必填
    ip:
    # 为空时使用 default_password
    username: root
    password:
    # 节点标签
    labels:
      - ccs: master
    tains:
# work 节点
nodes:
  - hostname: ""
    ip: ""
    password:
    labels:
      - ccs: node
    tains:
---
# 需要安装的扩展组件
install_plugins: ccs,ops
plugins:
  ccs:
    replicas: 1
  ops:
    replicas: 1
    key1: value1


---
# 集群 domin
cluster_domin: "cluster.local"
# 用于 k8s 证书双向认证
cert_sans:
cni:
  # 网络插件类型 为空时 不安装cni
  cni: "calico"
  # 开启 calico ipip
  calico_ipip: "off"
  # 网卡接口正则 用于 calico 推到网卡,为空时 calico 使用默认路由的网卡，example：eth* || ens*
  interface: ""
  pod_cidr: "10.1.0.0/16"
  service_cidr: "10.2.0.0/16"
proxy_mode: ipvs
ipvs:
  syncPeriod: 30s
  minSyncPeriod: 5s
  scheduler: rr

---
# kubeadm.k8s.io/v1beta2/ClusterConfiguration
clusterConfiguration:
  apiServer:
    extraArgs:
      authorization-mode: Node,RBAC
      max-mutating-requests-inflight: "4000"
      max-requests-inflight: "8000"
  controllerManager:
    extraArgs:
      kube-api-burst: "100"
      kube-api-qps: "50"
      terminated-pod-gc-threshold: "1"
  scheduler:
    extraArgs:
      kube-api-burst: "100"
      kube-api-qps: "50"


# kubeadm.k8s.io/v1beta2/InitConfiguration
matser:
  nodeRegistration:
    kubeletExtraArgs:
      kube-api-burst: "50"
      kube-api-qps: "40"
      eviction-hard: imagefs.available<5%,memory.available<100Mi,nodefs.available<5%,nodefs.inodesFree<5%
# kubeadm.k8s.io/v1beta2/JoinConfiguration
node:
  nodeRegistration:
    kubeletExtraArgs:
      kube-api-burst: "50"
      kube-api-qps: "40"
      eviction-hard: imagefs.available<5%,memory.available<100Mi,nodefs.available<5%,nodefs.inodesFree<5%



```
