### ISSUE TITLE
Clusterfile API upgrade.

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#314]
We need to encapsulate access to the *v1.Cluster data.
   For example, get  master IPList:
   Now we directly access the cluster.spec.master.IPlist
   but if we upgrade the cluster struct
   we need to update a lot of codes.
   So provide a function to get it is more Reasonable.

```
func (c *v1.Cluster)GetMasterIPList()([]string error){
     return cluster.spec.master.IPList
}
```

**Comment by fanux** [comment]
New Clusterfile spec suggestion:
1. support different hosts using different ssh config.
2. support different master or nodes flavor
3. Stripping Application Configuration, like calico network config. Using AppConfig and plugin to handle those configurations.

```
apiVersion: sealer.aliyun.com/v1alpha2
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: kubernetes:v1.19.9
  provider: BAREMETAL
  ENV: key=value
  ssh:
    # SSH login password, if you use the key to log in, you don’t need to set it
    passwd:
    ## The absolute path of the ssh private key file, for example /root/.ssh/id_rsa
    pk: xxx
    #  The password of the ssh private key file, if there is none, set it to ""
    pkPasswd: xxx
    # ssh login user
    user: root
    hosts:
    - name: master0
       role: master
       ip: 192.168.0.2
       ssh:
          passwd: xxxx # overwrite the spec.ssh.passwd
    - name: node0
       role: node
       ip: 192.168.0.3
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: AppConfig
metadata:
  name: calico-config
spec:
  data: |
    # in use NIC name
    interface: eth0
    # Network plug-in name
    cniName: calico
    podCIDR: 100.64.0.0/10
    svcCIDR: 10.96.0.0/22
    withoutCNI: false
```
