### ISSUE TITLE
upgrade cluster

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#35]
https://github.com/alibaba/sealer/blob/main/runtime/runtime.go#L13  

user upgrade kubenetes version:

1. Edit the cluster image in. sealer/[cluster name]/Clusterfile
  
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: registry.cn-qingdao.aliyuncs.com/sealer/cloudrootfs:v1.16.9-alpha.5 # upgrade it to cloudrootfs:v1.17.9 and save.
```

2. sealer apply -f  .sealer/[cluster name]/Clusterfile
