### ISSUE TITLE
Update document

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#367]
Incomplete documentation，How to use APP config

**Comment by fanux** [comment]
https://github.com/alibaba/sealer/blob/main/docs/design/global-config.md#application-config 

```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  name: mysql-config
spec:
  path: etc/mysql-values.yaml
  data: |
       mysql-user: root
       mysql-passwd: xxx
```

sealer will write the spec.data into etc/mysql-values.yaml, so you mysql using helm you can :

```
FROM kubernetes:v1.19.9
...
CMD helm install -f etc/mysql-values.yaml
```
