### ISSUE TITLE
Registry config

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#374]
Read the registry config from ${rootfs}/etc/registry.yaml,
The default config is 
```
domain: sea.hub 
# install it on master0
# using ${rootfs}/registry as volume
```

User can overwrite it by add a config:
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  name: REGISTRY
spec:
  path: etc/registry.yaml
  data: |
    domain: image.cai-inc.com
    ip: 172.16.0.1
    volume: /opt/registry
```
