### ISSUE TITLE
[EROR] [run.go:55] failed to found eth0 nic

### ISSUE THREAD

**Issue by willzhang** [alibaba/sealer#385]
#### What happened:
vmware workstation mechine install error

```
2021-07-05 19:20:28 [DEBG] [github.com/alibaba/sealer/vendor/github.com/sealyun/lvscare/utils/utils.go:21] SplitServer debug: IP: 10.103.97.2, Port: 6443
2021-07-05 19:20:28 [INFO] [sshcmd.go:48] [ssh][192.168.93.63] : kubeadm join --config=/var/lib/sealer/data/my-cluster/rootfs/kubeadm-join-config.yaml -v 0
2021-07-05 19:20:28 [INFO] [sshcmd.go:48] [ssh][192.168.93.64] : kubeadm join --config=/var/lib/sealer/data/my-cluster/rootfs/kubeadm-join-config.yaml -v 0
[preflight] Running pre-flight checks
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING FileExisting-socat]: socat not found in system path
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING FileExisting-socat]: socat not found in system path
        [WARNING Hostname]: hostname "k8s-node2" could not be reached
        [WARNING Hostname]: hostname "k8s-node2": lookup k8s-node2 on 114.114.114.114:53: no such host
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
        [WARNING Hostname]: hostname "k8s-node1" could not be reached
        [WARNING Hostname]: hostname "k8s-node1": lookup k8s-node1 on 8.8.8.8:53: no such host
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...

This node has joined the cluster:
* Certificate signing request was sent to apiserver and a response was received.
* The Kubelet was informed of the new secure connection details.

Run 'kubectl get nodes' on the control-plane to see this node join the cluster.

2021-07-05 19:20:35 [INFO] [sshcmd.go:48] [ssh][192.168.93.64] : mkdir -p /etc/kubernetes/manifests
2021-07-05 19:20:35 [INFO] [sshcmd.go:48] [ssh][192.168.93.64] : echo "apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-lvscare
  namespace: kube-system
spec:
  containers:
  - args:
    - care
    - --vs
    - 10.103.97.2:6443
    - --health-path
    - /healthz
    - --health-schem
    - https
    - --rs
    - 192.168.93.60:6443
    - --rs
    - 192.168.93.61:6443
    - --rs
    - 192.168.93.62:6443
    command:
    - /usr/bin/lvscare
    image: sea.hub:5000/fanux/lvscare:latest
    imagePullPolicy: IfNotPresent
    name: kube-lvscare
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib-modules
status: {}
" > /etc/kubernetes/manifests/kube-lvscare.yaml

This node has joined the cluster:
* Certificate signing request was sent to apiserver and a response was received.
* The Kubelet was informed of the new secure connection details.

Run 'kubectl get nodes' on the control-plane to see this node join the cluster.

2021-07-05 19:20:40 [INFO] [sshcmd.go:48] [ssh][192.168.93.63] : mkdir -p /etc/kubernetes/manifests
2021-07-05 19:20:40 [INFO] [sshcmd.go:48] [ssh][192.168.93.63] : echo "apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-lvscare
  namespace: kube-system
spec:
  containers:
  - args:
    - care
    - --vs
    - 10.103.97.2:6443
    - --health-path
    - /healthz
    - --health-schem
    - https
    - --rs
    - 192.168.93.60:6443
    - --rs
    - 192.168.93.61:6443
    - --rs
    - 192.168.93.62:6443
    command:
    - /usr/bin/lvscare
    image: sea.hub:5000/fanux/lvscare:latest
    imagePullPolicy: IfNotPresent
    name: kube-lvscare
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib-modules
status: {}
" > /etc/kubernetes/manifests/kube-lvscare.yaml
2021-07-05 19:20:40 [INFO] [init.go:236] start to install CNI
2021-07-05 19:20:40 [EROR] [run.go:55] failed to found eth0 nic
[root@k8s-master1 ~]# 
```

ip a
```
[root@k8s-master1 ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:7a:6c:c9 brd ff:ff:ff:ff:ff:ff
    inet 192.168.93.60/24 brd 192.168.93.255 scope global noprefixroute ens33
       valid_lft forever preferred_lft forever
    inet6 fe80::f7e2:c660:346d:b6d5/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:6d:40:6b:36 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
[root@k8s-master1 ~]# 
```

why default is eth0
```
[root@k8s-master1 ~]# cat /root/.sealer/my-cluster/Clusterfile 
apiVersion: zlink.aliyun.com/v1alpha1
kind: Cluster
metadata:
  creationTimestamp: null
  name: my-cluster
spec:
  certSANS:
  - aliyun-inc.com
  - 10.0.0.2
  image: kubernetes:v1.19.9
  masters:
    count: "1"
    cpu: "4"
    dataDisks:
    - "100"
    ipList:
    - 192.168.93.60
    - 192.168.93.61
    - 192.168.93.62
    memory: "4"
    systemDisk: "100"
  network:
    cniName: calico
    interface: eth0
    podCIDR: 100.64.0.0/10
    svcCIDR: 10.96.0.0/22
  nodes:
    count: "0"
    cpu: "4"
    dataDisks:
    - "100"
    ipList:
    - 192.168.93.63
    - 192.168.93.64
    memory: "4"
    systemDisk: "100"
  provider: BAREMETAL
  ssh:
    passwd: "123456"
    pk: /root/.ssh/id_rsa
    user: root
status: {}
```

#### Environment:
```
[root@k8s-master1 ~]# sealer version
{"gitVersion":"v0.2.1","gitCommit":"7a0c42b","buildDate":"2021-07-01 08:03:45","goVersion":"go1.14.15","compiler":"gc","platform":"linux/amd64"}
[root@k8s-master1 ~]# 
[root@k8s-master1 ~]# cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)
[root@k8s-master1 ~]# 
```
