### ISSUE TITLE
calico out of box

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#401]
Sealer now installs calico using a template, but the template is in [source code](https://github.com/alibaba/sealer/blob/main/guest/calico.go#L44) which is really not good.

Now sealer has the config feature, so we can completely not care about the CNI in source code, we treat it like a regular app.

When define a config in Clusterfile like this:

```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: registry.cn-qingdao.aliyuncs.com/sealer-app/my-SAAS-all-inone:latest
  provider: BAREMETAL
...
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  name: calico
spec:
  path: etc/calico-values.yaml
  data: |
      podcidr: x.x.x.x/xx
      IPIP: off
```
The config module will write the data to $rootfs/etc/calico-values.yaml (already done) 

So you just need to create a new Kubefile and build a calico CloudImage example:
```
FROM kubernetes:v1.19.9
COPY calico-crd .
CMD kubectl apply -f calico-crd
CMD kubectl apply -f etc/calico-values.yaml
```
`sealer build -t kubernetes-withcalico:v1.19.9 .`

Whats you needs to do?

1. Delete all the calico-related source code, like [v1.Cluster](https://github.com/alibaba/sealer/blob/main/types/api/v1/cluster_types.go#L28)  and apply CNI and calico template etc...
2. Write the calico Kubefile in https://github.com/alibaba/sealer/tree/main/applications/calico/vx.x.x
3. Build and test the CloudImage
4. Push the CloudImage to ACR hub
