### ISSUE TITLE
sealer plugins

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#445]
https://github.com/alibaba/sealer/blob/main/docs/design/plugin.md

1. dump plugin config, call plugins
2. hostname plugin
3. shell plugin
4. label plugin
5. etcd backup plugin

**Comment by fanux** [comment]
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
  name: ETCD_BACKUP
spec:
  action: Manual
  data: |
     alioss:
        ossendpoint: oss-cn-hangzhou.aliyuncs.com
        accesskeyid: *****
        accesskeysecrets: ****
        bucketname: etcdbackup
        objectpath: /sealos/
```
The action is Manual, you should trigle the plugin by yourself:
`sealer plugin -f etcd_backup.yaml` if not specify  the oss config, just save it on local disk.
