### ISSUE TITLE
Support --env for command `sealer run`

### ISSUE THREAD

**Issue by 27149chen** [alibaba/sealer#492]
## Issue Description

Type: *feature request*

### Describe what feature you want

Support --env for command `sealer run` so that we can customize the installation via environments params

**Comment by allencloud** [comment]
Could you be more specific? At last, where should the env be applied on? 

On each node's Operation System runtime? Or just on the installation process's lifecycle? @27149chen

**Comment by fanux** [comment]
@allencloud sealer Clusterfile has env feild, we can render the env values to yaml files or script to support some user defined config. like:

```
...
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  ports:
    - port: 443
      targetPort: {{ DashBoardPort }}
  selector:
    k8s-app: kubernetes-dashboard
...
```

`sealer run -e DashBoardPort=8443 mydashboard:latest`

@27149chen I think you can use the sealer config instead env:

https://github.com/alibaba/sealer/blob/main/docs/design/global-config.md#application-config
