### ISSUE TITLE
shell plugin support on field.

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#551]
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
  name: SHELL
spec:
  action: PostInstall
  on: 192.168.0.2
  data: |
     kubectl taint nodes node-role.kubernetes.io/master=:NoSchedule
```

If `spec.on` is not null, exec the shell command on that node, else exec it on every node.

https://github.com/alibaba/sealer/blob/main/plugin/shell_plugin.go
