### ISSUE TITLE
Support nodes with different SSH passwords

### ISSUE THREAD

**Issue by yj-cloud** [alibaba/sealer#578]
## Support nodes with different SSH passwords

Type: *feature request*

### Describe what feature you want
Support nodes with different SSH passwords in Clusterfile.

cluster.spec.ssh is the default password , the password in cluster.spec.masters can overwrite default.
Maybe just like this example.
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: kubernetes:v1.19.9
  provider: BAREMETAL
  ssh: # default password
    passwd: xxxx
    pk: ""
    pkPasswd: ""
    user: root
  masters:
  - ip: xx.xx.xx.1 # use default ssh
  - ip: xx.xx.xx.2
    ssh: # overwrite default 
      passwd: xxxx
      pk: ""
      pkPasswd: ""
      user: root
```

**Comment by fanux** [comment]
It's better to use a private key to access nodes witch don't have the same ssh passwd.

**Comment by yj-cloud** [comment]
> It's better to use a private key to access nodes witch don't have the same ssh passwd.

The point is not password or private key...
All of the nodes must use the same SSH now.

**Comment by fanux** [comment]
1. send ssh public key to all nodes
2. sealer support using private key, so this situation using ssh private key instead passwd.

**Comment by fanux** [comment]
```
ssh-keygen -t rsa
ssh-copyid remotenode
```
Clusterfile:
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: kubernetes:v1.19.9
  provider: BAREMETAL
  ssh: # default password
    pk: "id_rsa"
...
```
then sealer apply -f Clusterfile
