### ISSUE TITLE
docker run registry error. iptables: No chain/target/match by that name.

### ISSUE THREAD

**Issue by oldthreefeng** [alibaba/sealer#67]
#### What happened:

```
sealer apply -f clusterfile.yaml

```
#### What you expected to happen:

run success

#### How to reproduce it (as minimally and precisely as possible):
```
cat cluster.yaml
apiVersion: sealer.aliyun.com/v1alpha1
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: registry.cn-hongkong.aliyuncs.com/sealyun/kubernetes-amd64:v1.19.9
  provider: BAREMETAL
  ssh:
    passwd: centos
    user: root
  network:
    interface: ens33
    cniName: calico
    podCIDR: 100.64.0.0/10
    svcCIDR: 10.96.0.0/22
    withoutCNI: false
  certSANS:
    - aliyun-inc.com
    - 10.0.0.2
    
  masters:
    ipList:
     - 192.168.60.128 

```
#### Anything else we need to know?:
some logs.

```
Loaded image: registry:2.7.1
+ [[ -n /var/lib/sealer/data/my-cluster/registry ]]
+ docker run -d --restart=always --name seadent-registry -p 5000:5000 -v /var/lib/sealer/data/my-cluster/registry:/var/lib/registry registry:2.7.1
595e71d37d7aec10c89b38bb2e277ab7f5151699e350c2e48e176e3a071547f8
docker: Error response from daemon: driver failed programming external connectivity on endpoint seadent-registry (c169ccac09f30ee8201996eed31259dbe87e35f20bcb4637664de665ede5cbcd):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 5000 -j DNAT --to-destination 172.17.0.2:5000 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)).
2021-05-10 23:49:54 [EROR] exec command failed Process exited with status 125
2021-05-10 23:49:54 [EROR] exec command failed 192.168.60.128 cd /var/lib/sealer/data/my-cluster/scripts && sh init-registry.sh 5000 /var/lib/sealer/data/my-cluster/registry
[root@localhost ~]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[root@localhost ~]# docker run -d --restart=always --name seadent-registry -p 5000:5000 -v /var/lib/sealer/data/my-cluster/registry:/var/lib/registry registry:2.7.1
docker: Error response from daemon: Conflict. The container name "/seadent-registry" is already in use by container "595e71d37d7aec10c89b38bb2e277ab7f5151699e350c2e48e176e3a071547f8". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
[root@localhost ~]# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
595e71d37d7a        registry:2.7.1      "/entrypoint.sh /etc…"   57 seconds ago      Created                                 seadent-registry
[root@localhost ~]# docker logs -f 595
[root@localhost ~]# docker logs 595   
[root@localhost ~]# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
595e71d37d7a        registry:2.7.1      "/entrypoint.sh /etc…"   About a minute ago   Created                                 seadent-registry
[root@localhost ~]# iptables -vnL
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
[root@localhost ~]# iptables -vnL -t nat
Chain PREROUTING (policy ACCEPT 5 packets, 688 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 5 packets, 688 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 237 packets, 13300 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 237 packets, 13300 bytes)
 pkts bytes target     prot opt in     out     source               destination 
```
#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

find in iptables chain have no DOCKER chain.  but docker is runing normally(may usptream bug).

finally .  restart docker turns ok.

```
systemctl restart docker 
```
