### ISSUE TITLE
no application images cached sometimes

### ISSUE THREAD

**Issue by yj-cloud** [alibaba/sealer#736]
#### What happened:
I found no application images cached sometimes. 

**I got a correct cluster image in an ubuntu machine, but got a cluster image  no application images cached in this machine by the same command and kubefile. Is there any required software when I run sealer build？**

**There is no any error logs when I run sealer build -b lite.**

```
# kubefile
FROM kubernetes:v1.19.8
COPY helm bin/helm
COPY nginx charts/nginx
CMD helm install nginx charts/nginx --namespace example --create-namespace
# sealer version
{"gitVersion":"v0.5.0","gitCommit":"ff5db69","buildDate":"2021-09-28 02:44:09","goVersion":"go1.14.15","compiler":"gc","platform":"linux/amd64"}
# build command
sealer build -b lite -t test:yj .
[root@ecs6ejzdybkpr sealer]# uname -a
Linux ecs6ejzdybkpr.novalocal 5.14.3-1.el7.elrepo.x86_64 #1 SMP Fri Sep 10 13:17:45 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
[root@ecs6ejzdybkpr sealer]# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
[root@ecs6ejzdybkpr sealer]# sealer inspect test:yj
kind: Image
metadata:
  annotations:
    sea.aliyun.com/ClusterFile: |
      apiVersion: zlink.aliyun.com/v1alpha1
      kind: Cluster
      metadata:
        creationTimestamp: null
        name: my-cluster
      spec:
        certSANS:
        - aliyun-inc.com
        - 10.0.0.2
        image: test:yj
        masters:
          count: "1"
          cpu: "4"
          dataDisks:
          - "100"
          memory: "4"
          systemDisk: "100"
        network:
          podCIDR: 100.64.0.0/10
          svcCIDR: 10.96.0.0/22
        nodes:
          count: "0"
          cpu: "4"
          dataDisks:
          - "100"
          memory: "4"
          systemDisk: "100"
        provider: ALI_CLOUD
        ssh:
          passwd: Seadent123
          pk: xxx
          pkPasswd: xxx
          user: root
      status: {}
  creationTimestamp: null
spec:
  id: ab2e90e36969fd1caf67b1b2a777e5428a730eb2fef5f35dec54b8c7d6752452
  layers:
  - id: sha256:b6eb4360ad3ffe577c04d53205d0efc71dd59caef47bc5899230b291f292f593
    type: COPY
    value: . .
  - type: CMD
    value: kubectl apply -f etc/tigera-operator.yaml
  - type: CMD
    value: kubectl apply -f etc/custom-resources.yaml
  - id: sha256:66be641227e648390fc4fb71944468b7cd56b79d3a9f8cd9afafb879a1b58805
    type: COPY
    value: helm /bin
  - type: BASE
    value: registry cache
  - id: sha256:0202451acaea158823a57bbe3401652fef6d294bcf45fdb4d69279d0252243fd
    type: COPY
    value: nginx charts/nginx
  - type: CMD
    value: helm install nginx charts/nginx --namespace example --create-namespace
  - type: BASE
    value: registry cache
  platform: {}
  sealer_version: v0.5.0
status: {}

```

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
