### ISSUE TITLE
shell plugin workdir

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#757]
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
  name: SHELL
spec:
  action: PreInstall
  data: |
    cd /var/lib/sealer/data/my-cluster/rootfs/yrcloudfile && chmod 0755 all.sh && sh -x all.sh 192.168.13.28 8080
```
Using rootfs as shell plugin workdir, so user needn't cd rootfs
